# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-20 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_remove_comment_agora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agora',
            name='attachment_ptr',
        ),
        migrations.RemoveField(
            model_name='agora',
            name='author',
        ),
        migrations.DeleteModel(
            name='Agora',
        ),
    ]
