# Generated by Django 2.0.3 on 2018-03-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='return_date',
        ),
    ]
