# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_accept',
            field=models.SmallIntegerField(default=0),
        ),
    ]
