# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-11 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20180521_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-updated_date']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
