# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-19 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20180611_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tel_num',
            field=models.CharField(max_length=11),
        ),
    ]
